site_name: Wopee.io

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: '(prefers-color-scheme: light)'
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: '(prefers-color-scheme: dark)'
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wopee/
    - icon: fontawesome/brands/github
      link: https://github.com/Wopee-io

extra_css:
  - assets/bootstrap-grid.min.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

nav:
  - Home: index.md
  - About: /#who-we-are
  - Solutions: /#solutions
  - Team: /#team
  - Contact: /#contact-us
  - Book demo: book-demo.md