import React from "react";
import { useLocation } from "@docusaurus/router";
import Head from "@docusaurus/Head";

// Wraps every page. Used to inject a noindex meta on blog tag pages —
// they're auto-generated by the blog plugin, have no editable meta description,
// and offer thin SEO value (just a list of post links).
export default function Root({ children }: { children: React.ReactNode }) {
  const { pathname } = useLocation();
  const isBlogTagPage = pathname.startsWith("/blog/tags/");
  return (
    <>
      {isBlogTagPage && (
        <Head>
          <meta name="robots" content="noindex" />
        </Head>
      )}
      {children}
    </>
  );
}
