// Programmatic SEO page generator (#98).
//
// Reads data/pseo-pages.json and writes one .tsx landing page per entry into
// generated/pseo/. Each generated page is a thin wrapper that passes its data
// object to the shared <ProgrammaticPage> component (src/components/pseo/),
// which renders the styled landing layout (hero, CTA, comparison table, FAQ,
// related links) and emits the FAQ JSON-LD.
//
// A second @docusaurus/plugin-content-pages instance (see docusaurus.config.js,
// id: "pseo") serves that folder at the site root, so slug "ai-testing-react"
// is published at /ai-testing-react/.
//
// Runs before every build/start (see package.json), so the generated output is
// NOT committed (generated/ is gitignored). Reviewers review the component +
// the data (pseo-pages.json), not generated files.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DATA = path.join(ROOT, "data", "pseo-pages.json");
const OUT = path.join(ROOT, "generated", "pseo");

const labelFor = (page) =>
  page.category === "use-case" ? `AI ${page.subject}` : `AI Testing for ${page.subject}`;

function renderPage(page, bySlug) {
  // Only link to related pages that actually exist in the dataset, so we never
  // ship broken internal links while a batch is partial.
  const related = (page.related || [])
    .filter((slug) => bySlug[slug])
    .map((slug) => ({ slug, label: bySlug[slug].linkLabel }));

  const data = {
    slug: page.slug,
    category: page.category,
    subject: page.subject,
    keyword: page.keyword,
    title: page.title,
    description: page.description,
    aioOpener: page.aioOpener,
    problem: page.problem,
    solution: page.solution,
    steps: page.steps,
    comparison: page.comparison,
    faqs: page.faqs,
    related,
  };

  // JSON is a valid JS object literal, so it embeds directly in the .tsx.
  return `// AUTO-GENERATED by scripts/generate-pseo.js from data/pseo-pages.json — do not edit.
import React from "react";
import ProgrammaticPage, { type PseoData } from "@site/src/components/pseo/ProgrammaticPage";

const DATA: PseoData = ${JSON.stringify(data, null, 2)};

export default function Page() {
  return <ProgrammaticPage data={DATA} />;
}
`;
}

function main() {
  const raw = JSON.parse(fs.readFileSync(DATA, "utf8"));
  const pages = raw.pages || [];

  const bySlug = {};
  for (const p of pages) {
    bySlug[p.slug] = { ...p, linkLabel: labelFor(p) };
  }

  // Clean + recreate output dir so removed entries don't leave stale pages.
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  for (const page of pages) {
    fs.writeFileSync(path.join(OUT, `${page.slug}.tsx`), renderPage(page, bySlug));
  }

  console.log(`[pseo] generated ${pages.length} page(s) into generated/pseo/`);
}

main();
